spring:
  application:
    name: cm-eureka-authentication
  cloud:
    kubernetes:
      config:
        name: cm-eureka-authentication
        sources:
          - name: cm-eureka-authentication-${PROFILE}
  profiles:
    active: dev