apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-eureka-authentication
  labels:
    service: eureka-authentication
    app: hogarep
  namespace: default
spec:
  selector:
    matchLabels:
      service: eureka-authentication
      bd: mongo
  template:
    metadata:
      name: eureka-main-svc
      labels:
        service: eureka-authentication
        bd: mongo
    spec:
      containers:
        - name: eureka-authentication
          image: peterzinho16/eureka-authentication:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: container-port
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
          env:
            - name: SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-eureka-authentication
                  key: SERVER_PORT
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: secret-eureka-authentication
                  key: SPRING_DATA_MONGODB_URI
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%