apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: keycloak
  name: keycloak
spec:
  containers:
    - env:
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: host.docker.internal
        - name: DB_DATABASE
          value: keycloak
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: sql
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
      image: jboss/keycloak:latest
      name: keycloak
      ports:
        - containerPort: 8080
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}