apiVersion: v1
kind: Service
metadata:
  labels:
    run: keycloak
  name: keycloak
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30010
  selector:
    run: keycloak
  type: NodePort
status:
  loadBalancer: {}